routes/web.php
<?php
if (env('APP_ENV') === 'production') {
    URL::forceScheme('https');
}
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('command', 'CommandController');

Route::get('/createSqlite', 'CommandController@createSqlite');
Route::get('/truncateSqlite', 'CommandController@truncateSqlite');
Route::get('/init/setting', 'CommandController@initSetting');

Route::post('webhook', 'CommandController@webhookUpdate')->name('webhook');

Route::get('setting', 'UserController@editPassword')->name('setting');
Route::post('password/change', 'UserController@changePassword')->name('password.change');
Route::get('toggleswitch/{filter}', 'UserController@toggleSwitch')->name('toggleswitch');

Route::get('/edit/welcome', 'CommandController@editWelcomeMessage')->name('welcome.edit');
Route::post('/update/welcome', 'CommandController@updateWelcomeMessage')->name('welcome.update');

Route::get('/tes', 'CommandController@test');

app/Command.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Command extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'command', 'description', 'message', 'user_id', 'links', 'link_title',
    ];
}

app/Http/Controllers/CommandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Auth;
use Telegram\Bot\Keyboard\Keyboard;
use Carbon\Carbon;
use Validator;
use App\Command;
use App\Setting;
use Alert;
use Log;
use Telegram;
use DB;

class CommandController extends Controller
{
    private $client, $iduser, $clientBot, $idchat, $fname, $titleGroup, $btcprice, $ethprice, $bchprice, $btchigh, $btclow, $ethhigh, $ethlow, $bchhigh, $bchlow, $randomNum1, $randomNum2, $hasilCaptcha, $messageId, $volumeBtc, $volumeEth;
    private $luno, $indodax, $tokocrypto;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->only(['index', 'create', 'edit']);
        $this->client = new Client(['base_uri' => 'https://www.luno.com/ajax/1/']);
        $this->clientBot = new Client(['base_uri' => 'https://api.telegram.org/bot'.env('TELEGRAM_BOT_TOKEN', 'YOUR-BOT-TOKEN').'/']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cmds = Command::paginate(5);
        return \view('commands.index', \compact('cmds'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \view('commands.input');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'command'     => 'required|unique:commands|regex:/^\//',
            'message'  => 'required',
            'description'  => 'required',
            'link.*' => 'url|nullable'
        ]);

        try {
            $cmd = \trim($request->get('command'));
            $links = "[]";
            $link_titles = "[]";
            if (!is_null($request->link[0])) {
                $links = json_encode($request->get('link'));
                $link_titles = json_encode($request->get('link_title'));
            }
            $mes = Command::create([
                'command' => $cmd,
                'description' => $request->get('description'),
                'message' => $request->get('message'),
                'user_id' => Auth::user()->id,
                'links' => $links,
                'link_title' => $link_titles
            ]);

            Alert::success('Command succesfully inserted to a system', 'Yess..');

            return redirect()->route('command.index');
        } catch (\Exception $e) {
            Alert::error('Something went wrong'.$e->getMessage(), 'Oh no....');

            return redirect()->route('command.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cmd = Command::findOrFail($id);

        return \view('commands.edit', \compact('cmd'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'command'     => 'required|unique:commands,command,'.$id.'|regex:/^\//',
            'message'  => 'required',
            'description'  => 'required',
            'link.*' => 'url|nullable'
        ]);

        try {
            $cmd = Command::findOrFail($id);
            $cmnd = \trim($request->get('command'));
            $cmd->command = $cmnd;
            $cmd->description = $request->get('description');
            $cmd->message = $request->get('message');
            if (!is_null($request->link[0])) {
                $cmd->links = json_encode($request->get('link'));
                $cmd->link_title = json_encode($request->get('link_title'));
            } else if (is_null($request->link[0])){
                $cmd->links = "[]";
                $cmd->link_title = "[]";
            }

            $cmd->save();
            Alert::success('Command succesfully Updated', 'Yess..');

            return redirect()->route('command.index');
        } catch (\Exception $e) {
            Alert::error('Something went wrong', 'Oh no..');

            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $cmd = Command::findOrFail($id);
            $cmd->delete();
            Alert::success('Command succesfully deleted', 'Yess..');
        } catch (Exception $th) {
            Alert::error('Command was not succesfully deleted', 'Ooohhh...');
        }

        return redirect()->back();
    }

    public function tes()
    {
        try {
            DB::connection('sqlite')
                ->table('config')
                ->insert([
                'name' => 'filter bot',
                'value' => 'true'
            ]);
            echo 'Sqlite inserted';
        } catch (Exception $e) {
            return false;
        }
    }

    public function sendMessage($message, $btn = NULL)
    {
        if (isset($message)) {
            $txt = \strip_tags($message, '<br><a><b><i><code><pre><strong><em><br/>');
            $txt = str_replace('<br>',"\n",$txt);
            $txt = str_replace('<br />',"\n",$txt);
            $txt = html_entity_decode($txt);
            $txt = str_replace('@fname@',$this->fname,$txt);
            $txt = str_replace('@grouptitle@',$this->titleGroup,$txt);
            $txt = str_replace('@bitcoinprice@',$this->btcprice,$txt);
            $txt = str_replace('@bitcoinhigh@',$this->btchigh,$txt);
            $txt = str_replace('@bitcoinlow@',$this->btclow,$txt);
            $txt = str_replace('@ethereumprice@',$this->ethprice,$txt);
            $txt = str_replace('@ethereumhigh@',$this->ethhigh,$txt);
            $txt = str_replace('@ethereumlow@',$this->ethlow,$txt);
            $txt = str_replace('@bitcoincashprice@',$this->bchprice,$txt);
            $txt = str_replace('@bitcoincashhigh@',$this->bchhigh,$txt);
            $txt = str_replace('@bitcoincashlow@',$this->bchlow,$txt);
            $txt = str_replace('@lunobtcidrbuy@',"Rp. ".(isset($this->luno["btcidr"]["buy"]) ? $this->luno["btcidr"]["buy"] : "0"),$txt);
            $txt = str_replace('@lunobtcidrsell@',"Rp. ".(isset($this->luno["btcidr"]["sell"]) ? $this->luno["btcidr"]["sell"] : "0"),$txt);
            $txt = str_replace('@indobtcidrbuy@',"Rp. ".(isset($this->indodax["btcidr"]["buy"]) ? $this->indodax["btcidr"]["buy"] : "0"),$txt);
            $txt = str_replace('@indobtcidrsell@',"Rp. ".(isset($this->indodax["btcidr"]["sell"]) ? $this->indodax["btcidr"]["sell"] : "0"),$txt);
            // $txt = str_replace('@tokobtcidrbuy@',"Rp. ".(isset($this->tokocrypto["btcidr"]["buy"]) ? $this->tokocrypto["btcidr"]["buy"] : "0"),$txt);
            // $txt = str_replace('@tokobtcidrsell@',"Rp. ".(isset($this->tokocrypto["btcidr"]["sell"]) ? $this->tokocrypto["btcidr"]["sell"] : "0"),$txt);
            $txt = str_replace('@lunobchbtcbuy@',(isset($this->luno["bchbtc"]["buy"]) ? $this->luno["bchbtc"]["buy"] : "0"),$txt);
            $txt = str_replace('@lunobchbtcsell@',(isset($this->luno["bchbtc"]["sell"]) ? $this->luno["bchbtc"]["sell"] : "0"),$txt);
            $txt = str_replace('@indobchbtcbuy@',(isset($this->indodax["bchbtc"]["buy"]) ? $this->indodax["bchbtc"]["buy"] : "0"),$txt);
            $txt = str_replace('@indobchbtcsell@',(isset($this->indodax["bchbtc"]["sell"]) ? $this->indodax["bchbtc"]["sell"] : "0"),$txt);
            $txt = str_replace('@lunoethbtcbuy@',(isset($this->luno["ethbtc"]["buy"]) ? $this->luno["ethbtc"]["buy"] : "0"),$txt);
            $txt = str_replace('@lunoethbtcsell@',(isset($this->luno["ethbtc"]["sell"]) ? $this->luno["ethbtc"]["sell"] : "0"),$txt);
            $txt = str_replace('@indoethbtcbuy@',(isset($this->indodax["ethbtc"]["buy"]) ? $this->indodax["ethbtc"]["buy"] : "0"),$txt);
            $txt = str_replace('@indoethbtcsell@',(isset($this->indodax["ethbtc"]["sell"]) ? $this->indodax["ethbtc"]["sell"] : "0"),$txt);
            // $txt = str_replace('@tokoethbtcbuy@',(isset($this->tokocrypto["ethbtc"]["buy"]) ? $this->tokocrypto["ethbtc"]["buy"] : "0"),$txt);
            // $txt = str_replace('@tokoethbtcsell@',(isset($this->tokocrypto["ethbtc"]["sell"]) ? $this->tokocrypto["ethbtc"]["sell"] : "0"),$txt);
            // $txt = str_replace('@volumebtc@',$this->volumeBtc,$txt);
            // $txt = str_replace('@volumeeth@',$this->volumeEth,$txt);
            $txt = str_replace('@date@',$this->tanggalIndo(date('Y-m-d H:i:s')),$txt);
            if (isset($btn)) {
                $response = Telegram::sendMessage([
                    'chat_id' => $this->idchat,
                    'text' => $txt,
                    'parse_mode' => 'html',
                    'reply_markup'=>json_encode(['inline_keyboard' => $btn])
                ]);
            } else {
                $response = Telegram::sendMessage([
                    'chat_id' => $this->idchat,
                    'text' => $txt,
                    'parse_mode' => 'html'
                ]);
            }

            return $response;
        }
    }

    public function webhookUpdate()
    {
        $updates = Telegram::getWebhookUpdates();
        $cmd = $this->processMessage($updates);
        $msg = $this->getMessage($cmd);
        $btn = $this->getButton($cmd);

        return $this->sendMessage($msg,$btn);
    }

    /**
     * process message from webhook
     */

resources/views/commands/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
        <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Edit Command</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form role="form" method="POST" action="{{route('command.update', $cmd)}}" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                  <div class="card-body">
                    <div class="row" id="form-command">
                        <div class="form-group col-12">
                          <label for="exampleInputEmail1">Command</label>
                          <input type="text" name="command" class="form-control{{ $errors->has('command') ? ' is-invalid' : '' }}" value="{{$cmd->command}}" required>
                          <p class="help-block">
                            <strong>You have to use '/' in the first character of command</strong>
                          </p>
                          @if ($errors->has('command'))
                            <span class="invalid-feedback" role="alert">
                              <strong>{{ $errors->first('command') }}</strong>
                            </span>
                          @endif
                        </div>
                        <div class="form-group col-12">
                          <label for="message">Description</label>
                          <input type="text" name="description" class="form-control" value="{{$cmd->description}}" required>
                        </div>
                        <div class="form-group col-12">
                          <label for="message">Message</label>
                          <textarea rows="5" class="form-control" id="message" name="message" required>{{$cmd->message}}</textarea>
                          <p class="help-block">
                            <strong>You can use the word template below to show dynamic data (just put in anywhere in your message) :</strong>
                            <ul>
                              <li>
                                <b>@fname@ : </b> for showing first name of user
                              </li>
                              <li>
                                <b>@grouptitle@ : </b> for showing title of group (this is only work on group)
                              </li>
                              <li>
                                <b>@date@ : </b> for showing complete date ex: 'Thursday, 19 December 2019  01:27:49'
                              </li>
                            </ul>
                            <strong>You can use the word template below to show dynamic data <b>Only for /infoharga command</b> :</strong>
                            <ul>
                              <li>
                                <b>@bitcoinprice@ : </b> for showing actual Bitcoin price
                              </li>
                              <li>
                                <b>@bitcoinhigh@ : </b> for showing highest Bitcoin price in 24 hour
                              </li>
                              <li>
                                <b>@bitcoinlow@ : </b> for showing lowest Bitcoin price in 24 hour
                              </li>
                              <li>
                                <b>@ethereumprice@ : </b> for showing actual Ethereum price
                              </li>
                              <li>
                                <b>@ethereumhigh@ : </b> for showing highest Ethereum price in 24 hour
                              </li>
                              <li>
                                <b>@ethereumlow@ : </b> for showing lowest Ethereum price in 24 hour
                              </li>
                              <li>
                                <b>@bitcoincashprice@ : </b> for showing actual Bitcoin Cash price
                              </li>
                              <li>
                                <b>@bitcoincashhigh@ : </b> for showing highest Bitcoin Cash price in 24 hour
                              </li>
                              <li>
                                <b>@bitcoincashlow@ : </b> for showing lowest Bitcoin Cash price in 24 hour
                              </li>
                            </ul>
                            <strong>You can use the word template below to show dynamic data <b>Only for /infoexchange command</b> :</strong>
                            <ul>
                              <li>
                                <b>@lunobtcidrbuy@ : </b> for showing BTC/IDR from Luno
                              </li>
                              <li>
                                <b>@lunobtcidrsell@ : </b> for showing BTC/IDR from Luno
                              </li>
                              <li>
                                <b>@indobtcidrbuy@ : </b> for showing BTC/IDR from indodax
                              </li>
                              <li>
                                <b>@indobtcidrsell@ : </b> for showing BTC/IDR from indodax
                              </li>
                            //   <li>
                            //     <b>@tokobtcidrbuy@ : </b> for showing BTC/IDR from tokocrypto
                            //   </li>
                            //   <li>
                            //     <b>@tokobtcidrsell@ : </b> for showing BTC/IDR from tokocrypto
                            //   </li>
                              <li>
                                <b>@lunobchbtcbuy@ : </b> for showing BCH/BTC from Luno
                              </li>
                              <li>
                                <b>@lunobchbtcsell@ : </b> for showing BCH/BTC from Luno
                              </li>
                              <li>
                                <b>@indobchbtcbuy@ : </b> for showing BCH/BTC from indodax
                              </li>
                              <li>
                                <b>@indobchbtcsell@ : </b> for showing BCH/BTC from indodax
                              </li>
                              <li>
                                <b>@lunoethbtcbuy@ : </b> for showing ETH/BTC from Luno
                              </li>
                              <li>
                                <b>@lunoethbtcsell@ : </b> for showing ETH/BTC from Luno
                              </li>
                              <li>
                                <b>@indoethbtcbuy@ : </b> for showing ETH/BTC from indodax
                              </li>
                              <li>
                                <b>@indoethbtcsell@ : </b> for showing ETH/BTC from indodax
                              </li>
                            //   <li>
                            //     <b>@tokoethbtcbuy@ : </b> for showing ETH/BTC from tokocrypto
                            //   </li>
                            //   <li>
                            //     <b>@tokoethbtcsell@ : </b> for showing ETH/BTC from tokocrypto
                            //   </li>
                            </ul>
                          </p>
                        </div>
                          @if (!empty(\json_decode($cmd->links)))
                          @foreach (\json_decode($cmd->links) as $item)
                            <div class="form-group col-6 link{{$loop->index}}">
                              <label for="exampleInputEmail1">Link</label>
                              <input type="text" name="link[]" class="form-control" placeholder="Masukkan Link" value="{{$item}}">
                              <p class="help-block">
                                <strong>The url must start with "http://" or "https://"</strong>
                              </p>
                            </div>
                            @php
                                $title = json_decode($cmd->link_title);
                            @endphp
                            <div class="form-group col-3 link{{$loop->index}}">
                              <label for="exampleInputEmail1">Link Title</label>
                              <input type="text" name="link_title[]" class="form-control" placeholder="Masukkan Judul Link" value="{{$title[$loop->index]}}">
                            </div>
                            <div class="form-group col-3 link{{$loop->index}}">
                              <button type="button" id="remove" onclick="remove('link{{$loop->index}}');" class="btn btn-danger">Remove Link</button>
                            </div>
                          @endforeach
                          @else
                            <div class="form-group col-6">
                              <label for="exampleInputEmail1">Link</label>
                              <input type="text" name="link[]" class="form-control" placeholder="Input Link">
                              <p class="help-block">
                                <strong>The url must start with "http://" or "https://"</strong>
                              </p>
                            </div>
                            <div class="form-group col-3">
                              <label for="exampleInputEmail1">Link Title</label>
                              <input type="text" name="link_title[]" class="form-control" placeholder="Input Title Link">
                            </div>
                          @endif
                          <div class="form-group col-12">
                            <button type="button" id="add" class="btn btn-info">Add Link</button>
                          </div>
                    </div>
                  </div>

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                  </div>
                </form>
              </div>
</div>
<script>
  CKEDITOR.replace('message',{
    toolbarGroups : [
      { name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
      { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
      { name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
      { name: 'forms', groups: [ 'forms' ] },
      { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
      { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
      { name: 'links', groups: [ 'links' ] },
      { name: 'insert', groups: [ 'insert' ] },
      { name: 'styles', groups: [ 'styles' ] },
      { name: 'colors', groups: [ 'colors' ] },
      { name: 'tools', groups: [ 'tools' ] },
      { name: 'others', groups: [ 'others' ] },
      { name: 'about', groups: [ 'about' ] }
    ],

    removeButtons : 'Source,Save,NewPage,Preview,Print,Templates,Find,Replace,SelectAll,Scayt,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,Strike,Subscript,Superscript,Underline,RemoveFormat,CopyFormatting,NumberedList,Outdent,Blockquote,JustifyLeft,BidiLtr,BidiRtl,Language,JustifyRight,JustifyCenter,CreateDiv,Indent,BulletedList,JustifyBlock,Anchor,Unlink,Image,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,Format,Font,Styles,TextColor,BGColor,Maximize,ShowBlocks,FontSize',
    enterMode: CKEDITOR.ENTER_BR,
    shiftEnterMode: CKEDITOR.ENTER_BR,
    pasteFromWordPromptCleanup : true,
    pasteFromWordRemoveFontStyles : true,
    forcePasteAsPlainText : true,
    ignoreEmptyParagraph : true,
    removeFormatAttributes : true,
    on :
    {
      instanceReady : function( ev )
      {
        this.dataProcessor.writer.setRules( 'p',
        {
        indent : false,
        breakBeforeOpen : false,
        breakAfterOpen : false,
        breakBeforeClose : false,
        breakAfterClose : false
        });
        this.dataProcessor.writer.setRules( 'br',
        {
        indent : false,
        breakBeforeOpen : false,
        breakAfterOpen : false,
        breakBeforeClose : false,
        breakAfterClose : false
        });
      }
    }
  });
    jQuery(document).ready(function () {
        var l = 1000;
        $('#add').click(function () {
          l++;
          var index = "link"+l;
          var a =   '<div class="form-group col-12 '+index+'">'+
                    '<div>'+
                    '<label for="exampleInputEmail1">Link</label>'+
                    '<input type="text" name="link[]" class="form-control" placeholder="Input Link">'+
                    '<p class="help-block">'+
                    '<strong>The url must start with "http://" or "https://"</strong>'+
                    '</p>'+
                    '</div>'+
                    '<div>'+
                    '<label for="exampleInputEmail1">Link Title</label>'+
                    '<input type="text" name="link_title[]" class="form-control" placeholder="Input Link Title">'+
                    '</div>'+
                    '<div class="'+index+'">'+
                    '<button type="button" id="remove" onclick="remove(\''+index+'\');" class="btn btn-danger">Remove Link</button>'+
                    '</div>'+
                    '</div>';
          $('#form-command').append(a);
        });
    })
    function remove(params) {
      $("."+params).remove();
    }
</script>
@endsection

resources/views/commands/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
        <div class="card card-default">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-bullhorn"></i>
              Telegram Command
            </h3>
            <div class="card-tools">
                <ul class="nav nav-pills ml-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{route('command.create')}}" title="New Command"><i class="nav-icon fa fa-plus"></i></a>
                    </li>
                </ul>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
              @foreach ($cmds as $cmd)
              @if ($cmd->command != '@welcome')
              <div class="callout callout-info">
                <a href="javascript:void(0);" class="btn close" title="Remove Command" onclick="removeCommand({{$cmd->id}})"><i class="nav-icon fa fa-trash"></i></a>
                  <a class="btn close" href="{{route('command.edit', $cmd->id)}}" title="Edit Command"><i class="nav-icon fa fa-edit"></i></a>
                  <h5><b>{{$cmd->command}}</b></h5>
                  <p>{!!$cmd->message!!}</p>
                  @if (!empty($cmd->links))
                  <p>Button Link</p>
                      <ul>
                        @foreach (\json_decode($cmd->links) as $item)
                          @php
                            $title = json_decode($cmd->link_title);
                          @endphp
                          <li><a href="{{$item}}">{{$title[$loop->index]}}</a></li>
                        @endforeach
                      </ul>
                  @endif
              </div>
              @endif
                
              @endforeach

              {{$cmds->appends(Request::all())->links()}}
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
</div>
<script>
  function removeCommand(params) {
    var csrf_token = $('meta[name="csrf-token"]').attr("content");
    swal({
          title: 'Are You Sure?',
          text: "The deleted command can't be restored",
          type: 'warning',
          showCancelButton: true,
          confirmButtonClass: "red-thunderbird",
          cancelButtonClass: 'blue',
          confirmButtonText: 'Yes, I\'m Sure',
          cancelButtonText: 'No, cancel!',
        },
				function(isConfirm){
				  if (isConfirm){
            $.ajax({
              url: "{{ url('command') }}"+ '/' + params,
              type: "POST",
              data : {'_method' : 'DELETE', '_token' : csrf_token},
              success : function(){
                swal("Deleted!", "Command Successfully Deleted.", "success");
                location.reload();
              },
              error : function () {
                swal("Error!", "OOuuh the system ill.", "error");
              }
            })
				  }
        }
    );
  }
</script>
@endsection